version: '3.8'
services:
  lanchain1:
   container_name: lanchain-1
   restart: on-failure
   environment:
    - LCHAIN_NOS=3
    - LCHAIN_WHOAMI=lanchain-1
   build:
    context: .
    dockerfile: Dockerfile
   volumes:
    - .:/app
   networks:
    - lanchain
   ports:
    - 3030:3030
    - 14859:14859
    - 8091:8083
   expose:
    - 3030
    - 8083
   cap_add:
    - NET_ADMIN
    - NET_RAW

  lanchain2:
   container_name: lanchain-2
   restart: on-failure
   environment:
    - LCHAIN_NOS=3
    - LCHAIN_WHOAMI=lanchain-2
   build:
    context: .
    dockerfile: Dockerfile
   volumes:
    - .:/app
   networks:
    - lanchain
   ports:
    - 3032:3030
    - 8092:8083
   expose:
    - 3030
    - 8083
   cap_add:
    - NET_ADMIN
    - NET_RAW

  lanchain3:
   container_name: lanchain-3
   restart: on-failure
   environment:
    - LCHAIN_NOS=3
    - LCHAIN_WHOAMI=lanchain-3
   build:
    context: .
    dockerfile: Dockerfile
   volumes:
    - .:/app
   networks:
    - lanchain
   ports:
    - 3033:3030
    - 8093:8083
   expose:
    - 3030
    - 8083
   cap_add:
    - NET_ADMIN
    - NET_RAW

networks:
 lanchain:
  driver: bridge